# Generated by Django 5.0.4 on 2024-05-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField()),
                ("avatar_hash", models.CharField()),
                ("roles", models.ManyToManyField(to="core.userrole")),
            ],
        ),
    ]
