# Generated by Django 5.0.4 on 2024-05-08 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data_valid_until",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1971, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
