# Generated by Django 5.0.3 on 2024-04-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextmeeting',
            name='date_of_meeting',
            field=models.DateTimeField(verbose_name='Date of meeting'),
        ),
    ]
