# Generated by Django 5.0.6 on 2024-06-02 11:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_data_valid_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="permissions",
            field=models.CharField(
                choices=core.models.get_permission_choices, default=""
            ),
        ),
    ]
