# Generated by Django 5.0.6 on 2024-06-02 11:08

from django.db import migrations


def create_default_roles(apps, schema_editor):
    UserRole = apps.get_model("core", "UserRole")
    UserRole.objects.create(
        name="Genshiniara", id=1215012858346086461, permissions="Genshin"
    )
    UserRole.objects.create(
        name="Członek gwardii", id=1200540359919411380, permissions="Gwardia"
    )
    UserRole.objects.create(
        name="Z klasy", id=1148642506859368448, permissions="Klasowe"
    )


def remove_default_roles(apps, schema_editor):
    UserRole = apps.get_model("core", "UserRole")
    UserRole.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_userrole_permissions"),
    ]

    operations = [migrations.RunPython(create_default_roles, remove_default_roles)]
