# Generated by Django 5.0.4 on 2024-04-21 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gwardia', '0002_alter_nextmeeting_date_of_meeting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NextMeeting',
            new_name='Meeting',
        ),
    ]
