# Generated by Django 5.0.4 on 2024-04-22 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gwardia", "0002_alter_nextmeeting_date_of_meeting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nextmeeting",
            old_name="date_of_meeting",
            new_name="date",
        ),
    ]
