# Generated by Django 5.0.4 on 2024-04-19 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gwardia", "0003_rename_nextmeeting_meeting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting",
            old_name="date_of_meeting",
            new_name="date",
        ),
    ]
