# Generated by Django 5.0.4 on 2024-04-21 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gwardia", "0003_rename_date_of_meeting_meeting_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NextMeeting",
            new_name="Meeting",
        ),
    ]
